const load=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Cannot load '+src));image.src=src;});
const key='sologym-pixellab-barbarian-eight-256-r1';let decisions={};try{decisions=JSON.parse(localStorage.getItem(key)||'{}');}catch{}
const data=await fetch('/gallery.json').then(r=>{if(!r.ok)throw new Error('Gallery metadata unavailable');return r.json();});
const [room,bed,scene]=await Promise.all([load('/room.png'),load('/bed.png'),fetch('/scene.json').then(r=>r.json())]);
const cache=new Map();let selected=data.characters[0],roomMode='pixel',epoch=0;
document.querySelector('#cost').textContent=data.costSummary||'';
function preview(canvas,im,bounds,height=224){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.imageSmoothingEnabled=false;const [x,y,r,b]=bounds,w=r-x,h=b-y,k=Math.min(height/h,232/w);c.drawImage(im,x,y,w,h,(256-w*k)/2,240-h*k,w*k,h*k);}
function roomPreview(){const entry=cache.get(selected.id);if(!entry)return;const which=roomMode==='pixel'?'pixel':'source',im=entry[which],bounds=which==='pixel'?selected.alphaBounds:selected.sourceBounds;const [x,y,r,b]=bounds,w=r-x,h=b-y,k=scene.character.height*2/h;const canvas=document.querySelector('#room'),c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,1280,720);c.drawImage(room,0,0,1280,720);c.drawImage(bed,scene.bed.x*2,scene.bed.y*2,bed.width*2,bed.height*2);c.drawImage(im,x,y,w,h,scene.character.feet[0]*2-w*k/2,scene.character.feet[1]*2-h*k,w*k,h*k);}
function count(){document.querySelector('#count').textContent=data.characters.filter(x=>decisions[x.id]?.decision==='approved').length+' / 8 approved';}
async function choose(item){const ticket=++epoch;selected=item;document.querySelector('#title').textContent='PixelLab · '+item.label;document.querySelector('#dimensions').textContent=item.width+' × '+item.height+' total image · transparent';document.querySelector('#qa').textContent=item.qaSummary;document.querySelector('#download-one').href='/sprites/'+item.id+'.png';document.querySelector('#download-one').download=item.id+'-256.png';document.querySelector('#decision').value=decisions[item.id]?.decision||'pending';document.querySelector('#notes').value=decisions[item.id]?.notes||'';document.querySelector('#saved').textContent='';for(const b of document.querySelectorAll('#roster button'))b.setAttribute('aria-pressed',String(b.dataset.id===item.id));if(!cache.has(item.id)){const [source,pixel]=await Promise.all([load('/references/'+item.id+'.png'),load('/sprites/'+item.id+'.png')]);cache.set(item.id,{source,pixel});}if(ticket!==epoch)return;const images=cache.get(item.id);preview(document.querySelector('#source'),images.source,item.sourceBounds);preview(document.querySelector('#candidate'),images.pixel,item.alphaBounds);roomPreview();}
for(const item of data.characters){const b=document.createElement('button');b.dataset.id=item.id;b.setAttribute('aria-pressed','false');const im=document.createElement('img');im.src='/sprites/'+item.id+'.png';im.alt='';const label=document.createElement('span');label.textContent=item.label;b.append(im,label);b.onclick=()=>choose(item);document.querySelector('#roster').append(b);}
function save(){decisions[selected.id]={decision:document.querySelector('#decision').value,notes:document.querySelector('#notes').value};try{localStorage.setItem(key,JSON.stringify(decisions));document.querySelector('#saved').textContent='Saved on this browser. Export JSON to share the review.';}catch{document.querySelector('#saved').textContent='Browser storage unavailable; export your review before leaving.';}count();}
document.querySelector('#decision').onchange=save;document.querySelector('#notes').oninput=save;
for(const [id,mode] of [['pixel-room','pixel'],['source-room','source']])document.querySelector('#'+id).onclick=()=>{roomMode=mode;document.querySelector('#pixel-room').setAttribute('aria-pressed',String(mode==='pixel'));document.querySelector('#source-room').setAttribute('aria-pressed',String(mode==='source'));roomPreview();};
document.querySelector('#export-review').onclick=()=>{const review={schema:1,batch:data.batch,exportedAt:new Date().toISOString(),characters:data.characters.map(x=>({id:x.id,sourceSha256:x.sourceSha256,spriteSha256:x.spriteSha256,decision:decisions[x.id]?.decision||'pending',notes:decisions[x.id]?.notes||''}))};const url=URL.createObjectURL(new Blob([JSON.stringify(review,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='sologym-pixellab-barbarians-256-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
count();await choose(selected);
